## 00. PyTorch Fundamentals

Resources notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello I'm exicited to learn PyTorch")
print(torch.__version__)
print(torch.version.cuda)

Hello I'm exicited to learn PyTorch
2.5.1+cu121
12.1


## Intro to Tensors

### Creating Tensors
PyTorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

### **Scalar:** $τ$ → a single number

In [70]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [71]:
# scalar with no dimension
scalar.dim() # ndim is 

0

In [72]:
# Get tensor back as Python int
scalar.item()

7

### **Vector:** $τi$ → 1D list of numbers

In [73]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [74]:
vector.ndim
vector.dim()

1

In [75]:
vector.shape

torch.Size([2])

### **Matrix:** $τij$ → 2D grid (rows & columns)

In [76]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [77]:
MATRIX.dim()

2

In [78]:
MATRIX.shape

torch.Size([2, 2])

In [79]:
MATRIX[1]

tensor([ 9, 10])

### **Tensor:** $τijk$  → stack of matrices

In [80]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [81]:
TENSOR.ndim

3

In [82]:
TENSOR.shape

torch.Size([1, 3, 3])

In [83]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors
Why random tensors?