## 00. PyTorch Fundamentals

Resources notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello I'm exicited to learn PyTorch")
print(torch.__version__)
print(torch.version.cuda)

Hello I'm exicited to learn PyTorch
2.5.1+cu121
12.1


## Intro to Tensors

### Creating Tensors
PyTorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

### **Scalar:** $τ$ → a single number

In [70]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [71]:
# scalar with no dimension
scalar.dim() # ndim is 

0

In [72]:
# Get tensor back as Python int
scalar.item()

7

### **Vector:** $τi$ → 1D list of numbers

In [73]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [74]:
vector.ndim
vector.dim()

1

In [75]:
vector.shape

torch.Size([2])

### **Matrix:** $τij$ → 2D grid (rows & columns)

In [76]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [77]:
MATRIX.dim()

2

In [78]:
MATRIX.shape

torch.Size([2, 2])

In [79]:
MATRIX[1]

tensor([ 9, 10])

### **Tensor:** $τijk$  → stack of matrices

In [80]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [81]:
TENSOR.ndim

3

In [82]:
TENSOR.shape

torch.Size([1, 3, 3])

In [83]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors
Why random tensors?

Random tensors are important becuase the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data

`Start with random numbers -> look at the data -> update random numbers -> look at the data -> upfate random numbers`

Torch random tensors `torch.rand` = https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [126]:
# Create a random tensors of size (3,4)
# random_tensor = torch.rand(10, 10, 10)
random_tensor = torch.rand(3, 4)
random_tensor


tensor([[0.9504, 0.4062, 0.2511, 0.5584],
        [0.8691, 0.6104, 0.1904, 0.0687],
        [0.4436, 0.3845, 0.1001, 0.9467]])

In [ ]:
# Creata a random tensor with a similar shape to an image tensor
# An example of encoding data into Tensors
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, Width, Color Channels (R , G , B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 5]), 3)

### Zeros and Ones


In [106]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor #Zeros out or resets the tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [108]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [109]:
ones.dtype

torch.float32

In [110]:
random_tensor.dtype

torch.float32

In [111]:
random_image_size_tensor.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [115]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
torch.__version__

'2.5.1+cu121'

In [117]:
# Creating a tensors like
ten_zeros = torch.zeros_like(one_to_ten) 
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
float32 is the default
**Note:** Tensor datatypes is one of the is one 3 big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype, datatype mismatch
2. Tensors not right shape, shape or dimension mismatch
3. Tensors not on the right device, device mismatch

In [ ]:
# Float 32 Tensor
# float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # datetype is the tensor (e.g float16, float32, float64)
                               device=None, # what device your tensor is on "cuda", "cpu", etc.
                               requires_grad=False) # whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [121]:
float_32_tensor.dtype

torch.float16

In [ ]:
# Covnert from Float 32 to Float 16
float_16_tensor = float_32_tensor.type(torch.float16) 
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float64)