## 00. PyTorch Fundamentals

Resources notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello I'm exicited to learn PyTorch")
print(torch.__version__)
print(torch.version.cuda)

Hello I'm exicited to learn PyTorch
2.5.1+cu121
12.1


## Intro to Tensors

### Creating Tensors
PyTorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

### **Scalar:** $τ$ → a single number

In [70]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [71]:
# scalar with no dimension
scalar.dim() # ndim is 

0

In [72]:
# Get tensor back as Python int
scalar.item()

7

### **Vector:** $τi$ → 1D list of numbers

In [73]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [74]:
vector.ndim
vector.dim()

1

In [75]:
vector.shape

torch.Size([2])

### **Matrix:** $τij$ → 2D grid (rows & columns)

In [76]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [77]:
MATRIX.dim()

2

In [78]:
MATRIX.shape

torch.Size([2, 2])

In [79]:
MATRIX[1]

tensor([ 9, 10])

### **Tensor:** $τijk$  → stack of matrices

In [80]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [81]:
TENSOR.ndim

3

In [82]:
TENSOR.shape

torch.Size([1, 3, 3])

In [83]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors
Why random tensors?

Random tensors are important becuase the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data

`Start with random numbers -> look at the data -> update random numbers -> look at the data -> upfate random numbers`

Torch random tensors `torch.rand` = https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensors of size (3,4)
# random_tensor = torch.rand(10, 10, 10)
random_tensor = torch.rand(3, 4)
random_tensor


tensor([[[8.6005e-01, 1.5125e-01, 6.4383e-01, 9.1897e-01, 4.2428e-01,
          9.0995e-01, 6.8066e-01, 6.1727e-01, 5.9405e-01, 4.8622e-01],
         [6.3768e-01, 5.3605e-01, 4.5933e-02, 2.0271e-01, 4.6147e-01,
          2.2686e-01, 1.9908e-02, 8.6213e-01, 6.9771e-01, 6.0898e-01],
         [4.5337e-01, 9.3818e-03, 5.0853e-01, 2.2881e-01, 7.3407e-01,
          9.9559e-01, 4.7808e-01, 3.0896e-02, 8.8267e-01, 6.8596e-01],
         [9.3410e-01, 8.7784e-02, 1.8363e-01, 4.8240e-01, 6.8172e-01,
          8.2209e-01, 7.6313e-01, 8.3817e-01, 1.4535e-01, 9.0774e-01],
         [6.0462e-02, 9.8972e-01, 4.5331e-01, 5.7332e-02, 5.6935e-01,
          9.2817e-01, 8.1747e-01, 2.7828e-01, 3.0028e-01, 3.3617e-01],
         [9.7558e-01, 5.7895e-01, 7.7313e-01, 1.8910e-02, 9.9534e-01,
          7.9903e-01, 1.8630e-01, 8.0215e-01, 4.6308e-01, 3.4855e-01],
         [3.3051e-01, 3.2575e-01, 9.8361e-01, 7.9140e-01, 1.7805e-01,
          2.1365e-01, 1.7271e-02, 2.3526e-01, 4.9076e-01, 2.8267e-01],
         [1.6

In [85]:
random_tensor.ndim

2